USE QUANLYCONCUNG
GO

CREATE OR ALTER PROC USP_TIM_SANPHAM
@Find NVARCHAR(255)
AS
BEGIN
	DECLARE @FLAG AS BIT
	--THÔNG TIN SP (TÊN, MÃ SP, GIÁ, TÊN THƯƠNG HIỆU, SỐ LƯỢNG TỒN)
	IF NOT EXISTS (SELECT SP.MASP
					FROM SAN_PHAM SP
					WHERE SP.TEN_SP LIKE '%' + @Find + '%')
	BEGIN
		SET @FLAG = 0 -- TÌM THẤT BẠI
		PRINT N'TÌM KIẾM THẤT BẠI'
	END
		
	ELSE
		SET @FLAG = 1 --TÌM THÀNH CÔNG

	IF(@FLAG = 1)
	BEGIN
		--THÔNG TIN SP (TÊN, MÃ SP, GIÁ, TÊN THƯƠNG HIỆU)
		SELECT SP.MASP, SP.TEN_SP, SP.GIA_BAN, TH.TEN_TH, SP.LUOT_BINH_LUAN, SP.LUOT_YEU_THICH
		FROM SAN_PHAM SP JOIN THUONG_HIEU TH ON SP.MATH = TH.MATH
		WHERE SP.TEN_SP LIKE '%' + @Find + '%'
	END
END
GO

CREATE OR ALTER PROC USP_XEM_THONGTIN_SP
@MaSP INT
AS
BEGIN
	--THÔNG TIN SP (TÊN, MÃ SP, GIÁ, TÊN THƯƠNG HIỆU, SỐ LƯỢNG TỒN)
	SELECT SP.*, TH.TEN_TH
	FROM SAN_PHAM SP JOIN THUONG_HIEU TH ON SP.MATH = TH.MATH
	WHERE SP.MASP = @MaSP

	--NỘI DUNG CÁC BÌNH LUẬN CỦA SẢN PHẨM
	SELECT SP.MASP, SP.TEN_SP, KH.TENKH, BL.NOI_DUNG, BL.NGAY_DANG
	FROM SAN_PHAM SP JOIN BINH_LUAN BL ON BL.MASP = SP.MASP
	JOIN KHACH_HANG KH ON KH.MAKH = BL.MAKH
	WHERE SP.MASP = @MaSP
END
GO

--*
CREATE OR ALTER PROC USP_XEM_TTCHINHANH_DU_SLT_SP
@MASP INT
AS
BEGIN
	--THÔNG TIN CHI NHÁNH CÒN HÀNG
	SELECT B.MACN, B.SO_LUONG_TON, CN.SO_NHA_DUONG, CN.PHUONG_XA, CN.QUAN_TP, CN.TP_TINH, CN.SDT_CN
	FROM BAN B JOIN CHI_NHANH CN ON B.MACN = CN.MACN
	WHERE B.MASP = @MASP AND B.SO_LUONG_TON > 0
END
GO

--EXEC USP_TIM_SANPHAM N'Dép'
--EXEC USP_XEM_THONGTIN_SP 
--EXEC USP_XEM_TTCHINHANH_DU_SLT_SP

--Tìm sản phẩm thông qua tên loại hàng
GO
CREATE
--ALTER
PROC USP_TIM_SP_VOI_LH
	@TENLH NVARCHAR(100)
AS
BEGIN

	SELECT *
	FROM SAN_PHAM SP JOIN LOAI_HANG LH
	ON SP.MALH = LH.MALH
	WHERE TEN_LH LIKE N'%' + @TENLH + '%'

END
GO

--Tìm sản phẩm thông qua tên thương hiệu
GO
CREATE
--ALTER
PROC USP_TIM_SP_VOI_TH
	@TENTH NVARCHAR(100)
AS
BEGIN
	SELECT *
	FROM SAN_PHAM SP JOIN THUONG_HIEU TH
	ON SP.MATH = TH.MATH
	WHERE TEN_TH LIKE N'%' + @TENTH + '%'

END
GO

--Xem thống kê doanh thu của tất cả chi nhánh tại 1 ngày
GO
CREATE
--ALTER
PROC USP_TKDOANHTHU_THEONGAY
	@NGAY date
AS
BEGIN

	SELECT MACN, DOANH_THU
	FROM DOANH_THU
	WHERE NGAY_THONG_KE = @NGAY

END
GO

--TEST
EXEC USP_TIM_SP_VOI_LH 'men vi sinh'
EXEC USP_TIM_SP_VOI_TH 'Aveeno'
EXEC USP_TKDOANHTHU_THEONGAY '10-10-2020'

insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000001', '2020-10-10', 1200000)
insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000002', '2020-11-10', 1300000)
insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000003', '2020-10-10', 1400000)
insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000004', '2020-10-20', 1500000)
insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000005', '2020-12-10', 1600000)
