USE QUANLYCONCUNG
GO

-- INDEX --
--1. DON_HANG(TG_LAP_DH)
--2. CHI_NHANH(TP_TINH, QUAN_TP)
--3. KHACH_HANG(SDT_KH)
--4. SAN_PHAM(GIA_BAN)
--5. DON_HANG(TP_TINH, QUAN_TP)


-- TẠO THÊM CÁC BẢNG CÓ KÈM INDEX ĐỂ SO SÁNH
-- KHACH_HANG_INDEX
CREATE TABLE KHACH_HANG_INDEX (
	MAKH INT IDENTITY(100000,1),
	TENKH NVARCHAR(100),
	EMAIL_KH VARCHAR(60),
	SDT_KH CHAR(10),
	NGSINH_KH DATE,
	TONG_DIEM_TICH_LUY INT DEFAULT 0,
	MAT_KHAU VARCHAR(50) NOT NULL,
	TAI_KHOAN VARCHAR(50) NOT NULL UNIQUE,
	MA_THE INT,

	CONSTRAINT PK_KH_IDX PRIMARY KEY(MAKH),
	CONSTRAINT FK_KH_IDX_THE FOREIGN KEY(MA_THE) REFERENCES THE(MA_THE)

)
GO
SET IDENTITY_INSERT KHACH_HANG_INDEX ON
INSERT INTO KHACH_HANG_INDEX(MAKH,TENKH,EMAIL_KH,SDT_KH,NGSINH_KH,TONG_DIEM_TICH_LUY,MAT_KHAU,TAI_KHOAN,MA_THE)
SELECT KHACH_HANG.*
FROM KHACH_HANG
SET IDENTITY_INSERT KHACH_HANG_INDEX OFF

-- CÀI INDEX
CREATE NONCLUSTERED INDEX IDX_KH_SDT
ON KHACH_HANG_INDEX(SDT_KH)
INCLUDE(MAKH,TENKH,EMAIL_KH,NGSINH_KH,TONG_DIEM_TICH_LUY,MAT_KHAU,TAI_KHOAN)
-- END KHACH_HANG_INDEX

-- DON_HANG INDEX---
GO
CREATE TABLE DON_HANG_INDEX (
	MADH INT IDENTITY(100000,1) PRIMARY KEY,
	MAKH INT,
	MANV INT,
	MACN INT,
	MA_VOUCHER INT,
	PHI_SAN_PHAM MONEY DEFAULT 0,
	PHI_VAN_CHUYEN MONEY DEFAULT 0,
	PHI_GIAM MONEY DEFAULT 0,
	HINH_THUC_THANH_TOAN NVARCHAR(50) CHECK(HINH_THUC_THANH_TOAN IN (N'COD',N'ATM',N'VNPAY-QR',N'VISA',N'MASTERCARD',N'JCB',N'ZALOPAY',N'MOMO')),
	TONG_PHI AS (PHI_SAN_PHAM + PHI_VAN_CHUYEN - PHI_GIAM),
	SO_NHA_DUONG NVARCHAR(60),
	PHUONG_XA NVARCHAR(40),
	QUAN_TP NVARCHAR(40),
	TP_TINH NVARCHAR(40),
	TG_LAP_DH DATETIME NOT NULL,
	TRANG_THAI NVARCHAR(10) CHECK(TRANG_THAI IN (N'Chờ giao', N'Đã giao', N'Đã hủy')),
	TG_TRANG_THAI DATETIME,
	DIEM_TICH_LUY INT DEFAULT 0,

	CONSTRAINT FK_DH_IDX_KH FOREIGN KEY (MAKH)  REFERENCES KHACH_HANG(MAKH),
	CONSTRAINT FK_DH_IDX_NV  FOREIGN KEY (MANV)  REFERENCES NHAN_VIEN (MANV),
	CONSTRAINT FK_DH_IDX_CN  FOREIGN KEY (MACN)  REFERENCES CHI_NHANH (MACN),
	CONSTRAINT FK_DH_IDX_VOUCHER FOREIGN KEY (MA_VOUCHER) REFERENCES VOUCHER(MA_VOUCHER)
)

GO
-- COPY DỮ LIỆU --
SET IDENTITY_INSERT DON_HANG_INDEX ON
INSERT INTO DON_HANG_INDEX(MADH, MAKH, MANV, MACN, MA_VOUCHER, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, 
SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH, TRANG_THAI,  TG_TRANG_THAI, DIEM_TICH_LUY)
SELECT MADH, MAKH, MANV, MACN, MA_VOUCHER, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, 
SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH, TRANG_THAI,  TG_TRANG_THAI, DIEM_TICH_LUY
FROM DON_HANG
SET IDENTITY_INSERT DON_HANG_INDEX OFF
GO
-- CÀI INDEX
CREATE NONCLUSTERED INDEX IDX_DH_NGAYLAP
ON DON_HANG_INDEX(TG_LAP_DH) 

GO
CREATE NONCLUSTERED INDEX IDX_DH_DIACHI
ON DON_HANG_INDEX(TP_TINH, QUAN_TP)
INCLUDE (MAKH, MANV, MACN, MA_VOUCHER, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, TONG_PHI, SO_NHA_DUONG, PHUONG_XA, TG_LAP_DH, TRANG_THAI, TG_TRANG_THAI, DIEM_TICH_LUY) 

-- END DON_HANG INDEX

-- SAN_PHAM INDEX--
GO
CREATE TABLE SAN_PHAM_INDEX (
	MASP INT IDENTITY(100000,1),
	MALH INT,
	MATH INT NOT NULL,
	TEN_SP NVARCHAR(100),
	HINH_ANH VARCHAR(500),
	MO_TA NVARCHAR(1000),
	LUOT_YEU_THICH INT DEFAULT 0,
	LUOT_BINH_LUAN INT DEFAULT 0,
	GIA_BAN MONEY,

	CONSTRAINT PK_SAN_PHAM_IDX PRIMARY KEY(MASP),
	CONSTRAINT FK_SPIDX_LH FOREIGN KEY (MALH) REFERENCES LOAI_HANG (MALH),
	CONSTRAINT FK_SPIDX_TH FOREIGN KEY (MATH) REFERENCES THUONG_HIEU (MATH)
)

-- COPY DỮ LIỆU --
GO
SET IDENTITY_INSERT SAN_PHAM_INDEX ON
INSERT INTO SAN_PHAM_INDEX(MASP, MALH, MATH, TEN_SP, HINH_ANH, MO_TA, LUOT_YEU_THICH, LUOT_BINH_LUAN, GIA_BAN)
SELECT MASP, MALH, MATH, TEN_SP, HINH_ANH, MO_TA, LUOT_YEU_THICH, LUOT_BINH_LUAN, GIA_BAN
FROM SAN_PHAM
SET IDENTITY_INSERT SAN_PHAM_INDEX OFF
GO
-- CÀI INDEX
CREATE NONCLUSTERED INDEX IDX_SP_GIA
ON SAN_PHAM_INDEX(GIA_BAN)
INCLUDE (MASP, MATH, MALH, TEN_SP, HINH_ANH, MO_TA, LUOT_YEU_THICH, LUOT_BINH_LUAN)
-- END SAN_PHAM_INDEX

-- CHI_NHANH_INDEX
GO
CREATE TABLE CHI_NHANH_INDEX (
	MACN INT IDENTITY(100000,1),
	NVQL INT,
	SDT_CN CHAR(10),
	SO_NHA_DUONG NVARCHAR(60) UNIQUE,
	PHUONG_XA NVARCHAR(40),
	QUAN_TP NVARCHAR(40),
	TP_TINH NVARCHAR(40),

	CONSTRAINT PK_CNHANH_IDX PRIMARY KEY(MACN),
	CONSTRAINT FK_CN_IDX_NVQL FOREIGN KEY(NVQL) REFERENCES NHAN_VIEN (MANV)
)
GO
SET IDENTITY_INSERT CHI_NHANH_INDEX ON
INSERT INTO CHI_NHANH_INDEX(MACN, NVQL, SDT_CN, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH)
SELECT CHI_NHANH.*
FROM CHI_NHANH
SET IDENTITY_INSERT CHI_NHANH_INDEX OFF
GO
CREATE NONCLUSTERED INDEX IDX_CN_TINH_QUAN
ON CHI_NHANH_INDEX(TP_TINH,QUAN_TP)
INCLUDE (SO_NHA_DUONG, PHUONG_XA)
-- END CHI_NHANH_INDEX