use QUANLYCONCUNG
go

--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO THÁNG
CREATE 
--ALTER
PROC USP_THONGKE_THANG_CN
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MACN, MONTH(NGAY_THONG_KE) AS THANG, SUM(DOANH_THU) AS TONG_DOANH_THU
			FROM DOANH_THU
			WHERE YEAR(NGAY_THONG_KE) = @NAM
			GROUP BY MONTH(NGAY_THONG_KE), MACN
			ORDER BY MONTH(NGAY_THONG_KE) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO THÁNG
GO
CREATE 
--ALTER
PROC USP_THONGKE_THANG_TONG
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MONTH(NGAY_THONG_KE) AS THANG, SUM(DOANH_THU) AS TONG_DOANH_THU
			FROM DOANH_THU
			WHERE YEAR(NGAY_THONG_KE) = @NAM
			GROUP BY MONTH(NGAY_THONG_KE)
			ORDER BY MONTH(NGAY_THONG_KE) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO NĂM
GO
CREATE 
--ALTER
PROC USP_THONGKE_NAM_CN
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MACN, YEAR(NGAY_THONG_KE) AS NAM, SUM(DOANH_THU) AS TONG_DOANH_THU
			FROM DOANH_THU
			WHERE YEAR(NGAY_THONG_KE) = @NAM
			GROUP BY YEAR(NGAY_THONG_KE), MACN
			ORDER BY YEAR(NGAY_THONG_KE) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO NĂM
GO
CREATE 
--ALTER
PROC USP_THONGKE_NAM_TONG
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT YEAR(NGAY_THONG_KE) AS NAM, SUM(DOANH_THU) AS TONG_DOANH_THU
			FROM DOANH_THU
			WHERE YEAR(NGAY_THONG_KE) = @NAM
			GROUP BY YEAR(NGAY_THONG_KE)
			ORDER BY YEAR(NGAY_THONG_KE) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO NGÀY
GO
CREATE 
--ALTER
PROC USP_THONGKE_NGAY_CN
	@NGAY DATETIME
AS
BEGIN TRAN
	BEGIN TRY

		SELECT MACN, NGAY_THONG_KE AS NGAY, SUM(DOANH_THU) AS TONG_DOANH_THU
		FROM DOANH_THU
		WHERE NGAY_THONG_KE = @NGAY
		GROUP BY NGAY_THONG_KE, MACN
		ORDER BY NGAY_THONG_KE ASC

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO NGÀY
GO
CREATE 
--ALTER
PROC USP_THONGKE_NGAY_TONG
	@NGAY DATETIME
AS
BEGIN TRAN
	BEGIN TRY
	
		SELECT NGAY_THONG_KE AS NGAY, SUM(DOANH_THU) AS TONG_DOANH_THU
		FROM DOANH_THU
		WHERE NGAY_THONG_KE = @NGAY
		GROUP BY NGAY_THONG_KE
		ORDER BY NGAY_THONG_KE ASC

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC XÓA SẢN PHẨM
GO
CREATE 
--ALTER
PROC USP_XOA_SP
	@MASP INT
AS
BEGIN TRAN
	BEGIN TRY
	
		DELETE BINH_LUAN WHERE MASP = @MASP
		DELETE YEUTHICH WHERE MASP = @MASP
		DELETE BAN WHERE MASP = @MASP
		DELETE CHI_TIET_DON_HANG WHERE MASP = @MASP
		DELETE CHI_TIET_NHAP_HANG WHERE MASP = @MASP
		DELETE SAN_PHAM WHERE MASP = @MASP

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN