USE QUANLYCONCUNG
GO

SET IDENTITY_INSERT LOAI_HANG ON;
INSERT INTO LOAI_HANG (MALH, TEN_LH) values (-1, N'Không có')
SET IDENTITY_INSERT LOAI_HANG OFF;

--PROC XÓA LOẠI HÀNG
CREATE 
--ALTER
PROC USP_XOA_LH
	@MALH INT
AS
BEGIN TRAN
	BEGIN TRY
		
		--SET VỀ LOẠI HÀNG MẶC ĐỊNH MALH = -1
		UPDATE SAN_PHAM SET MALH = -1 WHERE MALH = @MALH 
		DELETE FROM LOAI_HANG WHERE MALH  = @MALH

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN
GO