use QUANLYCONCUNG
go

--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO THÁNG
CREATE 
--ALTER
PROC USP_THONGKE_THANG_CN
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MACN, MONTH(TG_LAP_DH) AS THANG, YEAR(TG_LAP_DH) AS NAM, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
			FROM DON_HANG
			WHERE YEAR(TG_LAP_DH) = @NAM AND TRANG_THAI = N'Đã giao'
			GROUP BY MONTH(TG_LAP_DH), MACN, YEAR(TG_LAP_DH)
			ORDER BY MONTH(TG_LAP_DH) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO THÁNG
GO
CREATE 
--ALTER
PROC USP_THONGKE_THANG_TONG
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MONTH(TG_LAP_DH) AS THANG, YEAR(TG_LAP_DH) AS NAM, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
			FROM DON_HANG
			WHERE YEAR(TG_LAP_DH) = @NAM AND TRANG_THAI = N'Đã giao'
			GROUP BY MONTH(TG_LAP_DH), YEAR(TG_LAP_DH)
			ORDER BY MONTH(TG_LAP_DH) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO NĂM
GO
CREATE 
--ALTER
PROC USP_THONGKE_NAM_CN
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MACN, YEAR(TG_LAP_DH) AS NAM, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
			FROM DON_HANG
			WHERE YEAR(TG_LAP_DH) = @NAM AND TRANG_THAI = N'Đã giao'
			GROUP BY MACN, YEAR(TG_LAP_DH)
			ORDER BY YEAR(TG_LAP_DH) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO NĂM
GO
CREATE 
--ALTER
PROC USP_THONGKE_NAM_TONG
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT YEAR(TG_LAP_DH) AS NAM, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
			FROM DON_HANG
			WHERE YEAR(TG_LAP_DH) = @NAM AND TRANG_THAI = N'Đã giao'
			GROUP BY YEAR(TG_LAP_DH)
			ORDER BY YEAR(TG_LAP_DH) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO NGÀY
GO
CREATE 
--ALTER
PROC USP_THONGKE_NGAY_CN
	@NGAY DATE
AS
BEGIN TRAN
	BEGIN TRY
		SELECT MACN, CONVERT(date, TG_LAP_DH) AS NGAY, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
		FROM DON_HANG
		WHERE  CONVERT(date, TG_LAP_DH) = @NGAY AND TRANG_THAI = N'Đã giao'
		GROUP BY MACN, CONVERT(date, TG_LAP_DH)
		ORDER BY NGAY ASC
	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO NGÀY
GO
CREATE 
--ALTER
PROC USP_THONGKE_NGAY_TONG
	@NGAY DATETIME
AS
BEGIN TRAN
	BEGIN TRY
	
		SELECT CONVERT(date, TG_LAP_DH) AS NGAY, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
		FROM DON_HANG
		WHERE  CONVERT(date, TG_LAP_DH) = '2021-07-24' AND TRANG_THAI = N'Đã giao'
		GROUP BY CONVERT(date, TG_LAP_DH)
		ORDER BY NGAY ASC

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC XÓA SẢN PHẨM
GO
CREATE 
--ALTER
PROC USP_XOA_SP
	@MASP INT
AS
BEGIN TRAN
	BEGIN TRY
	
		DELETE BINH_LUAN WHERE MASP = @MASP
		DELETE YEUTHICH WHERE MASP = @MASP
		DELETE BAN WHERE MASP = @MASP
		DELETE CHI_TIET_DON_HANG WHERE MASP = @MASP
		DELETE CHI_TIET_NHAP_HANG WHERE MASP = @MASP
		DELETE SAN_PHAM WHERE MASP = @MASP

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN