USE QUANLYCONCUNG
GO


-- PROCEDURE: Thêm chi tiết đơn hàng
CREATE OR ALTER 
PROC USP_THEM_CTDH 
@MADH INT, @MASP INT, @SL INT, @GIAM_GIA INT
AS
BEGIN
	IF NOT EXISTS(SELECT MADH FROM DON_HANG WHERE MADH = @MADH)
	BEGIN
		RAISERROR(N'Không tồn tại đơn hàng!', 16,1)
		RETURN
	END
	DECLARE @THANH_TIEN MONEY
	DECLARE @MACN INT
	SELECT @THANH_TIEN = (SELECT SP.GIA_BAN * @SL
						FROM SAN_PHAM SP
						WHERE SP.MASP = @MASP
						)
	SELECT @MACN = MACN FROM DON_HANG DH WHERE MADH = @MADH

	INSERT CHI_TIET_DON_HANG(MADH, MASP, SO_LUONG_MUA, GIAM_GIA, THANH_TIEN_MUA) VALUES (@MADH, @MASP, @SL, @GIAM_GIA, @THANH_TIEN)
	UPDATE DON_HANG
	SET DON_HANG.PHI_SAN_PHAM += @THANH_TIEN
	WHERE DON_HANG.MADH = @MADH
	UPDATE BAN
	SET SO_LUONG_TON = SO_LUONG_TON - @SL,
		SO_LUONG_DA_BAN = SO_LUONG_DA_BAN + @SL
	WHERE BAN.MASP = @MASP AND MACN = @MACN
END
GO
-- PROCEDURE: Khi cập nhật số lượng mua hoặc phần trăm giảm giá của chi tiết đơn hàng
CREATE OR ALTER PROC USP_UPDATE_SLMUA_GIAM_GIA_CTDH
@MADH INT, @MASP INT, @SO_LUONG_MUA INT, @GIAM_GIA INT
AS BEGIN
	IF NOT EXISTS(SELECT MADH FROM CHI_TIET_DON_HANG WHERE MADH = @MADH AND MASP = @MASP)
	BEGIN
		RAISERROR(N'Không tồn tại chi tiết đơn hàng!', 16,1)
		RETURN
	END
	-- CẬP NHẬT GIAM_GIA
	IF (@SO_LUONG_MUA IS NULL)
	BEGIN
		UPDATE CT
		SET GIAM_GIA = @GIAM_GIA, THANH_TIEN_MUA = SO_LUONG_MUA * (SAN_PHAM.GIA_BAN  - SAN_PHAM.GIA_BAN* @GIAM_GIA / 100)
		FROM CHI_TIET_DON_HANG CT JOIN SAN_PHAM ON CT.MASP = SAN_PHAM.MASP
		WHERE CT.MASP = @MASP AND CT.MADH = @MADH
	END
	-- CẬP NHẬT SO_LUONG_MUA
	ELSE IF (@GIAM_GIA IS NULL)
	BEGIN
		UPDATE CT
		SET SO_LUONG_MUA = @SO_LUONG_MUA, THANH_TIEN_MUA = @SO_LUONG_MUA * (SAN_PHAM.GIA_BAN  - SAN_PHAM.GIA_BAN* GIAM_GIA / 100)
		FROM CHI_TIET_DON_HANG CT JOIN SAN_PHAM ON CT.MASP = SAN_PHAM.MASP
		WHERE CT.MASP = @MASP AND CT.MADH = @MADH
	END
	-- Cập nhật phí sản phẩm ở DON_HANG
	UPDATE DON_HANG SET PHI_SAN_PHAM = (SELECT SUM(CT.THANH_TIEN_MUA)
										FROM CHI_TIET_DON_HANG CT
										WHERE CT.MADH = @MADH)
	WHERE MADH = @MADH
END


-- UPDATE TOÀN BỘ DỮ LIỆU THÀNH TIỀN Ở CHI TIẾT ĐƠN HÀNG
GO
CREATE OR ALTER PROC USP_UPDATE_ALL_CTDH
AS BEGIN
	-- CẬP NHẬT GIAM_GIA
	UPDATE CT
		SET THANH_TIEN_MUA = SO_LUONG_MUA * (SAN_PHAM.GIA_BAN  - SAN_PHAM.GIA_BAN* GIAM_GIA / 100)
		FROM CHI_TIET_DON_HANG CT JOIN SAN_PHAM ON CT.MASP = SAN_PHAM.MASP
	-- Cập nhật phí sản phẩm ở DON_HANG
	UPDATE DON_HANG SET PHI_SAN_PHAM = (SELECT SUM(CT.THANH_TIEN_MUA)
										FROM CHI_TIET_DON_HANG CT
										WHERE CT.MADH = DON_HANG.MADH)
END

-- PROC: XÓA CHI_TIET_DON_HANG
GO
CREATE OR ALTER 
PROC USP_XOA_CTDH
@MADH INT, @MASP INT
AS
BEGIN
	IF NOT EXISTS(SELECT MADH FROM CHI_TIET_DON_HANG WHERE MADH = @MADH AND MASP = @MASP)
	BEGIN
		RAISERROR(N'Không tồn tại chi tiết đơn hàng!', 16,1)
		RETURN
	END
	DECLARE @SL INT, @MACN INT
	SELECT @SL = SO_LUONG_MUA FROM CHI_TIET_DON_HANG WHERE MADH = @MADH AND MASP = @MASP
	SELECT @MACN = MACN FROM DON_HANG WHERE MADH = @MADH

	UPDATE DON_HANG
	SET PHI_SAN_PHAM -= (SELECT THANH_TIEN_MUA FROM CHI_TIET_DON_HANG 
							WHERE MADH = @MADH AND MASP = @MASP)
	WHERE MADH = @MADH 

	UPDATE BAN
	SET SO_LUONG_TON = SO_LUONG_TON + @SL
	WHERE BAN.MACN = @MACN AND BAN.MASP = @MASP

	DELETE CHI_TIET_DON_HANG WHERE MADH = @MADH AND MASP = @MASP
END



-- PROCEDURE: Update SO_LUONG_NHAP hoặc DON_GIA_NHAP của CHI TIET NHAP HANG
GO
CREATE OR ALTER PROC USP_UPDATE_CT_NHAP_HANG
@MAPN INT, @MASP INT, @SL INT, @DON_GIA INT
AS
BEGIN
	IF NOT EXISTS(SELECT MAPN FROM CHI_TIET_NHAP_HANG WHERE MAPN = @MAPN AND MASP = @MASP)
	BEGIN
		RAISERROR(N'Không tồn tại chi tiết nhập hàng!', 16,1)
		RETURN
	END
	DECLARE @SL_BD INT
	SELECT @SL_BD = SO_LUONG_NHAP FROM CHI_TIET_NHAP_HANG 
	WHERE MAPN = @MAPN AND MASP = @MASP
	UPDATE BAN
	SET SO_LUONG_TON = SO_LUONG_TON - @SL_BD + @SL
	FROM PHIEU_NHAP_HANG PN  
	WHERE PN.MACN = BAN.MACN
	AND PN.MAPN = @MAPN AND BAN.MASP = @MASP
	
	IF (@SL IS NULL) UPDATE CHI_TIET_NHAP_HANG SET DON_GIA_NHAP = @DON_GIA
	ELSE IF (@DON_GIA IS NULL)  UPDATE CHI_TIET_NHAP_HANG SET SO_LUONG_NHAP = @SL
	-- Update lại TONG_TIEN_NHAP ở PHIEU_NHAP_HANG
	UPDATE PHIEU_NHAP_HANG
	SET TONG_TIEN_NHAP = ( SELECT SUM(CTNH.THANH_TIEN_NHAP)
						   FROM CHI_TIET_NHAP_HANG CTNH
						   WHERE CTNH.MAPN = @MAPN
						  )
	WHERE PHIEU_NHAP_HANG.MAPN = @MAPN
END

GO
-- PROCEDURE: Update voucher của đơn hàng
CREATE OR ALTER PROC USP_UPDATE_VOUCHER_DH
@MADH INT, @MA_VOUCHER INT
AS
BEGIN
	IF (@MADH NOT IN (SELECT MADH FROM DON_HANG) OR @MA_VOUCHER NOT IN (SELECT MA_VOUCHER FROM VOUCHER))
	BEGIN
		RAISERROR(N'MADH hoặc MA_VOUCHER không hợp lệ!', 16,1)
		RETURN
	END
	DECLARE @MAKH INT
	SELECT @MAKH = MAKH FROM DON_HANG WHERE MADH = @MAKH
	IF (@MA_VOUCHER IS NOT NULL)
	BEGIN
		UPDATE DON_HANG
		SET DON_HANG.MA_VOUCHER = @MA_VOUCHER, DON_HANG.PHI_GIAM = (SELECT CASE 
								WHEN DON_HANG.TG_LAP_DH BETWEEN V.TG_BAT_DAU AND V.TG_KET_THUC 
									THEN(CASE 
											WHEN V.PHAN_TRAM_GIAM_GIA = 0 OR (DON_HANG.PHI_SAN_PHAM * V.PHAN_TRAM_GIAM_GIA / 100) >= V.GIAM_TOI_DA THEN V.GIAM_TOI_DA
											WHEN (DON_HANG.PHI_SAN_PHAM * V.PHAN_TRAM_GIAM_GIA / 100) < V.GIAM_TOI_DA THEN DON_HANG.PHI_SAN_PHAM * V.PHAN_TRAM_GIAM_GIA / 100
									END)
								WHEN DON_HANG.TG_LAP_DH NOT BETWEEN V.TG_BAT_DAU AND V.TG_KET_THUC THEN 0
								END
								FROM VOUCHER V 
								WHERE DON_HANG.MADH = @MADH
								AND V.MA_VOUCHER = @MA_VOUCHER
								)
		WHERE DON_HANG.MADH = @MADH
	END
	ELSE UPDATE DON_HANG SET MA_VOUCHER = @MA_VOUCHER, PHI_GIAM = 0 WHERE MADH = @MADH

	UPDATE DH
	SET DIEM_TICH_LUY = (PHI_SAN_PHAM - PHI_GIAM)/ 100 *  THE.PHAN_TRAM_TICH_LUY
	FROM DON_HANG DH JOIN KHACH_HANG KH ON DH.MAKH = KH.MAKH
	JOIN THE ON THE.MA_THE = KH.MA_THE
	WHERE MADH = @MADH

	UPDATE KHACH_HANG
	SET TONG_DIEM_TICH_LUY = (SELECT SUM(DIEM_TICH_LUY)
								FROM DON_HANG DH WHERE DH.MAKH = @MAKH AND DH.MADH = @MADH)
	WHERE KHACH_HANG.MAKH = @MAKH
	
END

GO
-- PROC: Thêm đơn hàng
CREATE OR ALTER PROC USP_THEM_DON_HANG
@MAKH INT, @MANV INT, @MA_VOUCHER INT, @PHI_VAN_CHUYEN MONEY, @HTTT NVARCHAR(50), @TG_LAP_DH DATETIME
AS
BEGIN
	IF (@MAKH NOT IN (SELECT MAKH FROM KHACH_HANG) OR @MA_VOUCHER NOT IN (SELECT MA_VOUCHER FROM VOUCHER)
	OR @MANV NOT IN (SELECT MANV FROM NHAN_VIEN))
	BEGIN
		RAISERROR(N'MAKH, MANV hoặc MA_VOUCHER không hợp lệ!', 16,1)
		RETURN
	END
	DECLARE @MACN INT
	SELECT @MACN = NHAN_VIEN.MACN FROM NHAN_VIEN WHERE NHAN_VIEN.MANV = @MANV

	INSERT DON_HANG(MAKH, MANV, MACN, MA_VOUCHER, PHI_VAN_CHUYEN, HINH_THUC_THANH_TOAN, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH)
	VALUES (@MAKH, @MANV, @MACN, @MA_VOUCHER, @PHI_VAN_CHUYEN, @HTTT, NULL, NULL, NULL, NULL, @TG_LAP_DH)

	UPDATE DON_HANG
	SET SO_NHA_DUONG = DC.SO_NHA_DUONG, PHUONG_XA = DC.PHUONG_XA, QUAN_TP = DC.QUAN_TP, TP_TINH = DC.TP_TINH
	FROM DIA_CHI_KH DC
	WHERE MAC_DINH = 1 AND DON_HANG.MADH = @MAKH
	AND DC.MAKH = @MAKH

END

GO
-- PROC: THÊM CHI_TIET_NHAP_HANG
CREATE OR ALTER 
PROC USP_THEM_CT_NHAP_HANG 
@MAPN INT, @MASP INT, @SL INT, @DON_GIA INT
AS
BEGIN
	IF (@MAPN NOT IN (SELECT MAPN FROM CHI_TIET_NHAP_HANG) OR @MASP NOT IN (SELECT MASP FROM SAN_PHAM))
	BEGIN
		RAISERROR(N'MAPN hoặc MASP không hợp lệ!', 16,1)
		RETURN
	END
	DECLARE @MACN INT
	SELECT @MACN = MACN FROM PHIEU_NHAP_HANG WHERE MAPN = @MAPN
	INSERT CHI_TIET_NHAP_HANG(MAPN, MASP, SO_LUONG_NHAP, DON_GIA_NHAP) VALUES (@MAPN, @MASP, @SL, @DON_GIA)
	UPDATE PHIEU_NHAP_HANG
	SET TONG_SO_MAT_HANG += 1, TONG_TIEN_NHAP += @SL*@DON_GIA
	WHERE MAPN = @MAPN 

	UPDATE BAN
	SET SO_LUONG_TON = SO_LUONG_TON + @SL
	WHERE BAN.MACN = @MACN AND BAN.MASP = @MASP
END
GO

-- PROC: XÓA CHI_TIET_NHAP_HANG
CREATE OR ALTER 
PROC USP_XOA_CT_NHAP_HANG 
@MAPN INT, @MASP INT
AS
BEGIN
	IF NOT EXISTS(SELECT MAPN FROM CHI_TIET_NHAP_HANG WHERE MAPN = @MAPN AND MASP = @MASP)
	BEGIN
		RAISERROR(N'Không tồn tại chi tiết nhập hàng!', 16,1)
		RETURN
	END
	DECLARE @SL INT, @MACN INT
	SELECT @SL = SO_LUONG_NHAP FROM CHI_TIET_NHAP_HANG WHERE MAPN = @MAPN AND MASP = @MASP
	SELECT @MACN = MACN FROM PHIEU_NHAP_HANG WHERE MAPN = @MAPN

	UPDATE PHIEU_NHAP_HANG
	SET TONG_SO_MAT_HANG -= 1, TONG_TIEN_NHAP -= (SELECT THANH_TIEN_NHAP FROM CHI_TIET_NHAP_HANG 
													WHERE MAPN = @MAPN AND MASP = @MASP)
	WHERE MAPN = @MAPN 

	UPDATE BAN
	SET SO_LUONG_TON = SO_LUONG_TON - @SL
	WHERE BAN.MACN = @MACN AND BAN.MASP = @MASP

	DELETE CHI_TIET_NHAP_HANG WHERE MAPN = @MAPN AND MASP = @MASP
END


GO
-- PROC: Update trạng thái của đơn hàng
CREATE OR ALTER 
PROC USP_UPDATE_TRANG_THAI
@MaDH INT, @TrangThai NVARCHAR(10), @ThoiGian DATETIME
AS
BEGIN
	IF NOT EXISTS(SELECT MADH FROM DON_HANG WHERE MADH = @MaDH)
	BEGIN
		RAISERROR(N'Không tồn tại đơn hàng!', 16,1)
		RETURN
	END
	DECLARE @TTBanDau NVARCHAR(10), @TGBanDau DATETIME
	SELECT @TTBanDau = DH.TRANG_THAI, @TGBanDau = DH.TG_TRANG_THAI
	FROM DON_HANG DH
	WHERE DH.MADH = @MaDH
	IF (@TGBanDau > @ThoiGian)
	BEGIN
		PRINT N'LỖI: Thời gian trạng thái mới < Thời gian trạng thái hiện tại'
		RETURN 1 -- Không thành công
	END
	IF (@TTBanDau IN (N'Đã giao', N'Đã hủy'))
	BEGIN
		PRINT N'Không cập nhật trạng thái đơn hàng khi đơn hàng đã giao / đã hủy'
		RETURN 1
	END
	IF (@TrangThai = N'Chờ giao' AND @TTBanDau IS NOT NULL)
	BEGIN
		PRINT N'Trạng thái phải cập nhật theo thứ tự: Chờ giao -> Đã giao/Đã hủy'
		RETURN 1
	END
	UPDATE DON_HANG SET TRANG_THAI = @TrangThai, TG_TRANG_THAI = @ThoiGian
	WHERE MADH = @MaDH
	IF (@TrangThai = N'Đã giao')
	BEGIN
		DECLARE @PHI MONEY,  @MANV INT
		SELECT @MANV = MANV, @PHI = PHI_SAN_PHAM  FROM DON_HANG WHERE MADH = @MaDH
		UPDATE NHAN_VIEN
		SET TONG_DON_BAN +=1, TONG_TIEN_BAN += @PHI
		WHERE MANV = @MANV
	END
	RETURN 0 -- Cập nhật thành công
END


-- Mỗi khách hàng chỉ có duy nhất 1 địa chỉ mặc định
GO
CREATE OR ALTER
PROC USP_ADD_DIA_CHI_MAC_DINH
@MaKH INT, @STT INT
AS
BEGIN
	IF NOT EXISTS(SELECT MAKH FROM DIA_CHI_KH WHERE MAKH = @MaKH AND STT = @STT)
	BEGIN
		RAISERROR(N'Không tồn tại địa chỉ cần tìm!', 16,1)
		RETURN
	END
	UPDATE DIA_CHI_KH SET MAC_DINH = 1 WHERE MAKH = @MaKH AND STT = @STT
	UPDATE DIA_CHI_KH SET MAC_DINH = 0 WHERE MAKH = @MaKH AND STT != @STT
END


-- Hiệu suất làm việc của nhân viên thay đổi khi update MANV (nhân viên quản lý đơn hàng) của bảng DON_HANG
-- Update nhân viên phụ trách đơn hàng
GO
CREATE OR ALTER 
PROC USP_UPDATE_NV_DH
@NVSau INT, @MaDH INT
AS
BEGIN
	IF (@NVSau NOT IN (SELECT MANV FROM NHAN_VIEN) OR @MADH NOT IN (SELECT MADH FROM DON_HANG))
	BEGIN
		RAISERROR(N'Không tồn tại nhân viên hoặc đơn hàng!', 16,1)
		RETURN
	END
	DECLARE @NVBanDau CHAR(8), @TongTien MONEY
	SELECT @NVBanDau = MANV, @TongTien = PHI_SAN_PHAM FROM DON_HANG
	WHERE MADH = @MaDH

	IF (@NVBanDau = @NVSau)
	BEGIN
		PRINT N'Nhân viên không thay đổi!'
		RETURN 0 -- Thành công
	END
	UPDATE NHAN_VIEN SET TONG_DON_BAN -=1, TONG_TIEN_BAN -= @TongTien
	WHERE MANV = @NVBanDau
	UPDATE NHAN_VIEN SET TONG_DON_BAN +=1, TONG_TIEN_BAN += @TongTien
	WHERE MANV = @NVSau
	UPDATE DON_HANG SET MANV = @NVSau WHERE MADH = @MaDH
	RETURN 0
END

GO
	-- Thêm địa chỉ khách hàng (Tự động tính STT tiếp theo, không cần chèn vào)
CREATE OR ALTER PROC USP_INSERT_DIA_CHI_KH
@MAKH INT, @SONHA NVARCHAR(60), @PHUONG NVARCHAR(40), @QUAN NVARCHAR(40), @TP NVARCHAR(40), @MAC_DINH BIT
AS
BEGIN
IF (@MAKH NOT IN (SELECT MAKH FROM KHACH_HANG))
	BEGIN
		RAISERROR(N'Không tồn tại nhân viên hoặc đơn hàng!', 16,1)
		RETURN
	END
	DECLARE @STT INT
	SELECT @STT = ISNULL(MAX(STT),0)+1
    FROM DIA_CHI_KH
    WHERE MAKH = @MAKH
	IF (@MAC_DINH = 1)
	BEGIN
		EXEC USP_ADD_DIA_CHI_MAC_DINH @MAKH, @STT
	END
	INSERT DIA_CHI_KH VALUES (@MAKH, @STT, @SONHA, @PHUONG, @QUAN, @TP, @MAC_DINH)
END


	-- Xóa địa chỉ khách hàng
GO
CREATE OR ALTER PROC USP_DELETE_DIA_CHI_KH
@MAKH INT, @STT INT
AS
BEGIN
	IF NOT EXISTS(SELECT MAKH FROM DIA_CHI_KH WHERE MAKH = @MaKH AND STT = @STT)
	BEGIN
		RAISERROR(N'Không tồn tại địa chỉ cần tìm!', 16,1)
		RETURN
	END
	DECLARE @MAX_STT INT
	SELECT @MAX_STT = MAX(STT) FROM DIA_CHI_KH
	DELETE DIA_CHI_KH WHERE MAKH = @MAKH AND STT = @STT
	UPDATE DIA_CHI_KH SET STT = @STT WHERE STT = @MAX_STT
END

			------------------------------------------ PROCEDURE TEST INDEX ---------------------------------------
GO
CREATE OR ALTER PROC USP_TIM_SANPHAM
@Find NVARCHAR(255)
AS
BEGIN
	DECLARE @FLAG AS BIT
	--THÔNG TIN SP (TÊN, MÃ SP, GIÁ, TÊN THƯƠNG HIỆU, SỐ LƯỢNG TỒN)
	IF NOT EXISTS (SELECT SP.MASP
					FROM SAN_PHAM SP
					WHERE SP.TEN_SP LIKE '%' + @Find + '%')
	BEGIN
		SET @FLAG = 0 -- TÌM THẤT BẠI
		PRINT N'TÌM KIẾM THẤT BẠI'
	END
		
	ELSE
		SET @FLAG = 1 --TÌM THÀNH CÔNG

	IF(@FLAG = 1)
	BEGIN
		--THÔNG TIN SP (TÊN, MÃ SP, GIÁ, TÊN THƯƠNG HIỆU)
		SELECT SP.MASP, SP.TEN_SP, SP.GIA_BAN, TH.TEN_TH, SP.LUOT_BINH_LUAN, SP.LUOT_YEU_THICH
		FROM SAN_PHAM SP JOIN THUONG_HIEU TH ON SP.MATH = TH.MATH
		WHERE SP.TEN_SP LIKE '%' + @Find + '%'
	END
END
GO

CREATE OR ALTER PROC USP_XEM_THONGTIN_SP
@MaSP INT
AS
BEGIN
	--THÔNG TIN SP (TÊN, MÃ SP, GIÁ, TÊN THƯƠNG HIỆU, SỐ LƯỢNG TỒN)
	SELECT SP.*, TH.TEN_TH
	FROM SAN_PHAM SP JOIN THUONG_HIEU TH ON SP.MATH = TH.MATH
	WHERE SP.MASP = @MaSP

	--NỘI DUNG CÁC BÌNH LUẬN CỦA SẢN PHẨM
	SELECT SP.MASP, SP.TEN_SP, KH.TENKH, BL.NOI_DUNG, BL.NGAY_DANG
	FROM SAN_PHAM SP JOIN BINH_LUAN BL ON BL.MASP = SP.MASP
	JOIN KHACH_HANG KH ON KH.MAKH = BL.MAKH
	WHERE SP.MASP = @MaSP
END
GO

--*
CREATE OR ALTER PROC USP_XEM_TTCHINHANH_DU_SLT_SP
@MASP INT
AS
BEGIN
	--THÔNG TIN CHI NHÁNH CÒN HÀNG
	SELECT B.MACN, B.SO_LUONG_TON, CN.SO_NHA_DUONG, CN.PHUONG_XA, CN.QUAN_TP, CN.TP_TINH, CN.SDT_CN
	FROM BAN B JOIN CHI_NHANH CN ON B.MACN = CN.MACN
	WHERE B.MASP = @MASP AND B.SO_LUONG_TON > 0
END

GO
-- PROC: XEM THÔNG TIN ĐƠN HÀNG THEO KHU VỰC 
CREATE OR ALTER
PROC USP_XEM_DH_THEO_KV
@TP_Tinh NVARCHAR(40),
@Q_TP NVARCHAR(40)
AS
BEGIN

	IF EXISTS (SELECT MADH
				FROM DON_HANG_INDEX WHERE TP_TINH = @TP_Tinh AND QUAN_TP = @Q_TP)
	BEGIN
		SELECT MADH, MAKH, MANV, MACN, MA_VOUCHER, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, TONG_PHI, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH, TRANG_THAI, TG_TRANG_THAI, DIEM_TICH_LUY 
		FROM DON_HANG_INDEX WHERE TP_TINH = @TP_Tinh AND QUAN_TP = @Q_TP
		RETURN
	END
	
	IF EXISTS (SELECT MADH
				FROM DON_HANG_INDEX WHERE TP_TINH = @TP_Tinh)
	BEGIN
		SELECT MADH, MAKH, MANV, MACN, MA_VOUCHER, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, TONG_PHI, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH, TRANG_THAI, TG_TRANG_THAI, DIEM_TICH_LUY 
		FROM DON_HANG_INDEX WHERE TP_TINH = @TP_Tinh
		RETURN
	END

	PRINT N'Vui lòng nhập thành phố (tỉnh) hoặc quận (thành phố)!!!'
END
GO

--Tìm sản phẩm thông qua tên loại hàng
GO
CREATE OR ALTER
PROC USP_TIM_SP_VOI_LH
	@TENLH NVARCHAR(100)
AS
BEGIN

	SELECT *
	FROM SAN_PHAM SP JOIN LOAI_HANG LH
	ON SP.MALH = LH.MALH
	WHERE TEN_LH LIKE N'%' + @TENLH + '%'

END
GO

--Tìm sản phẩm thông qua tên thương hiệu
GO
CREATE OR ALTER
PROC USP_TIM_SP_VOI_TH
	@TENTH NVARCHAR(100)
AS
BEGIN
	SELECT *
	FROM SAN_PHAM SP JOIN THUONG_HIEU TH
	ON SP.MATH = TH.MATH
	WHERE TEN_TH LIKE N'%' + @TENTH + '%'

END
GO


-- FLOW ĐẶT HÀNG --
-- EXEC USP_THEM_DON_HANG --> EXEC USP_THEM_CTDH (thêm đủ các mặt hàng) --> EXEC USP_UPDATE_VOUCHER_DH để tính phí giảm, tổng phí và điểm tích lũy cuối cùng.


								-- PROCEDURE SỬ DỤNG TRONG UI --

SET IDENTITY_INSERT LOAI_HANG ON
INSERT INTO LOAI_HANG (MALH, TEN_LH) values (-1, N'Không có')
SET IDENTITY_INSERT LOAI_HANG OFF

--PROC XÓA LOẠI HÀNG
GO
CREATE OR ALTER PROC USP_XOA_LH
	@MALH INT
AS
BEGIN TRAN
	BEGIN TRY	
		--SET VỀ LOẠI HÀNG MẶC ĐỊNH MALH = -1
		UPDATE SAN_PHAM SET MALH = -1 WHERE MALH = @MALH 
		DELETE FROM LOAI_HANG WHERE MALH  = @MALH

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

GO
--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO THÁNG
CREATE OR ALTER PROC USP_THONGKE_THANG_CN
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MACN, MONTH(TG_LAP_DH) AS THANG, YEAR(TG_LAP_DH) AS NAM, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
			FROM DON_HANG
			WHERE YEAR(TG_LAP_DH) = @NAM AND TRANG_THAI = N'Đã giao'
			GROUP BY MONTH(TG_LAP_DH), MACN, YEAR(TG_LAP_DH)
			ORDER BY MONTH(TG_LAP_DH) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO THÁNG
GO
CREATE OR ALTER PROC USP_THONGKE_THANG_TONG
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MONTH(TG_LAP_DH) AS THANG, YEAR(TG_LAP_DH) AS NAM, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
			FROM DON_HANG
			WHERE YEAR(TG_LAP_DH) = @NAM AND TRANG_THAI = N'Đã giao'
			GROUP BY MONTH(TG_LAP_DH), YEAR(TG_LAP_DH)
			ORDER BY MONTH(TG_LAP_DH) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO NĂM
GO
CREATE OR ALTER PROC USP_THONGKE_NAM_CN
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT MACN, YEAR(TG_LAP_DH) AS NAM, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
			FROM DON_HANG
			WHERE YEAR(TG_LAP_DH) = @NAM AND TRANG_THAI = N'Đã giao'
			GROUP BY MACN, YEAR(TG_LAP_DH)
			ORDER BY YEAR(TG_LAP_DH) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO NĂM
GO
CREATE OR ALTER PROC USP_THONGKE_NAM_TONG
	@NAM INT
AS
BEGIN TRAN
	BEGIN TRY
	
	IF @NAM < 0  
		BEGIN
			RAISERROR('Năm không hợp lệ! ',16,1)
		END
	ELSE
		BEGIN
			SELECT YEAR(TG_LAP_DH) AS NAM, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
			FROM DON_HANG
			WHERE YEAR(TG_LAP_DH) = @NAM AND TRANG_THAI = N'Đã giao'
			GROUP BY YEAR(TG_LAP_DH)
			ORDER BY YEAR(TG_LAP_DH) ASC
		END

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU CHI NHÁNH THEO NGÀY
GO
CREATE OR ALTER PROC USP_THONGKE_NGAY_CN
	@NGAY DATE
AS
BEGIN TRAN
	BEGIN TRY
		SELECT MACN, CONVERT(date, TG_LAP_DH) AS NGAY, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
		FROM DON_HANG
		WHERE  CONVERT(date, TG_LAP_DH) = @NGAY AND TRANG_THAI = N'Đã giao'
		GROUP BY MACN, CONVERT(date, TG_LAP_DH)
		ORDER BY NGAY ASC
	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC THỐNG KÊ DOANH THU TỔNG THEO NGÀY
GO
CREATE OR ALTER PROC USP_THONGKE_NGAY_TONG
	@NGAY DATETIME
AS
BEGIN TRAN
	BEGIN TRY
	
		SELECT CONVERT(date, TG_LAP_DH) AS NGAY, SUM(PHI_SAN_PHAM) AS TONG_DOANH_THU
		FROM DON_HANG
		WHERE  CONVERT(date, TG_LAP_DH) = @NGAY AND TRANG_THAI = N'Đã giao'
		GROUP BY CONVERT(date, TG_LAP_DH)
		ORDER BY NGAY ASC

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN

--PROC XÓA SẢN PHẨM
GO
CREATE OR ALTER PROC USP_XOA_SP
	@MASP INT
AS
BEGIN TRAN
	BEGIN TRY
	
		DELETE BINH_LUAN WHERE MASP = @MASP
		DELETE YEUTHICH WHERE MASP = @MASP
		DELETE BAN WHERE MASP = @MASP
		DELETE CHI_TIET_DON_HANG WHERE MASP = @MASP
		DELETE CHI_TIET_NHAP_HANG WHERE MASP = @MASP
		DELETE SAN_PHAM WHERE MASP = @MASP

	END TRY

	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN	
	END CATCH
COMMIT TRAN
RETURN


GO
-- PROC: Tìm sản phẩm theo thương hiệu
CREATE OR ALTER
PROC USP_TIM_TEN_THUONG_HIEU
	@MATH INT,
	@TEN_TH NVARCHAR(20) OUTPUT
AS
BEGIN
	IF @MATH IS NOT NULL
	BEGIN
		SELECT @TEN_TH = (SELECT TEN_TH
		FROM THUONG_HIEU
		WHERE MATH = @MATH)
	END
END

GO
-- PROC: Tìm tên loại hàng
CREATE OR ALTER
PROC USP_TIM_LOAI_HANG
	@MALH INT,
	@TEN_LH NVARCHAR(20) OUTPUT
AS
BEGIN
	IF @MALH IS NOT NULL
	BEGIN
		SELECT @TEN_LH = (SELECT TEN_LH
		FROM LOAI_HANG
		WHERE MALH = @MALH)
	END
END


