USE QUANLYCONCUNG
GO
CREATE OR ALTER 
PROC uspTimDiaChiCN
(
	@QuanFlag AS BIT,
	@Quan AS NVARCHAR(40),
	@TPFlag AS BIT,
	@Tpho AS NVARCHAR(40)
)
AS
BEGIN
	IF @QuanFlag = 1 AND @TPFlag = 0
	BEGIN
		SELECT MACN, SO_NHA_DUONG,
			PHUONG_XA, QUAN_TP, TP_TINH
		FROM CHI_NHANH CN 
		WHERE QUAN_TP = @Quan
		RETURN
	END
	IF @TPFlag = 1 AND @QuanFlag = 0
	BEGIN
		SELECT MACN, SO_NHA_DUONG, 				PHUONG_XA, QUAN_TP, TP_TINH
		FROM CHI_NHANH CN 
		WHERE TP_TINH = @Tpho
		RETURN
	END
	IF @TPFlag = 1 AND @QuanFlag = 1
	BEGIN
		SELECT MACN, SO_NHA_DUONG, 				PHUONG_XA, QUAN_TP, TP_TINH
		FROM CHI_NHANH CN 
		WHERE TP_TINH = @Tpho 
			AND QUAN_TP = @Quan
		RETURN
	END
	ELSE RETURN
END

GO
CREATE OR ALTER
PROC uspTimKH
(
	@IDKH AS CHAR(8)
)
AS
BEGIN
	SELECT MAKH, TENKH, EMAIL_KH, 			SDT_KH, NGSINH_KH
	FROM KHACH_HANG
	WHERE MAKH = @IDKH
END


EXEC uspTimDiaChiCN 1,2,0,N'Kon Tum'
EXEC uspTimDiaChiCN 1,2,1,N'Kon Tum'
EXEC uspTimDiaChiCN 0,2,1,N'Kon Tum'
EXEC uspTimKH 'KH000001'