use QUANLYCONCUNG

--Tìm sản phẩm thông qua mã sp hay tên sp
GO
CREATE
--ALTER
PROC USP_TIM_SP_VOI_MASP_TENSP
	@MASP CHAR(8),
	@TENSP NVARCHAR(100)
AS
BEGIN
	IF @MASP IS NOT NULL
	BEGIN
		SELECT MASP, MALH, MATH, TEN_SP, HINH_ANH, MO_TA, LUOT_YEU_THICH, LUOT_BINH_LUAN, GIA_BAN
	FROM SAN_PHAM
	WHERE MASP = @MASP
	END

	IF @TENSP IS NOT NULL
	BEGIN
	SELECT MASP, MALH, MATH, TEN_SP, HINH_ANH, MO_TA, LUOT_YEU_THICH, LUOT_BINH_LUAN, GIA_BAN
	FROM SAN_PHAM
	WHERE TEN_SP LIKE N'%' + @TENSP + '%'
	END	
END
GO

--Tìm sản phẩm thông qua tên loại hàng
GO
CREATE
--ALTER
PROC USP_TIM_SP_VOI_LH
	@TENLH NVARCHAR(100)
AS
BEGIN

	SELECT *
	FROM SAN_PHAM SP JOIN LOAI_HANG LH
	ON SP.MALH = LH.MALH
	WHERE TEN_LH LIKE N'%' + @TENLH + '%'

END
GO

--Tìm sản phẩm thông qua tên thương hiệu
GO
CREATE
--ALTER
PROC USP_TIM_SP_VOI_TH
	@TENTH NVARCHAR(100)
AS
BEGIN

	SELECT *
	FROM SAN_PHAM SP JOIN THUONG_HIEU TH
	ON SP.MATH = TH.MATH
	WHERE TEN_TH LIKE N'%' + @TENTH + '%'

END
GO

--Xem thống kê doanh thu của tất cả chi nhánh tại 1 ngày
GO
CREATE
--ALTER
PROC USP_TKDOANHTHU_THEONGAY
	@NGAY date
AS
BEGIN

	SELECT MACN, DOANH_THU
	FROM DOANH_THU
	WHERE NGAY_THONG_KE = @NGAY

END
GO


--TEST
EXEC USP_TIM_SP_VOI_MASP_TENSP 1, NULL
EXEC USP_TIM_SP_VOI_MASP_TENSP NULL, 'Vitamin D'

EXEC USP_TIM_SP_VOI_LH 'men vi sinh'

EXEC USP_TIM_SP_VOI_TH 'Aveeno'

EXEC USP_TKDOANHTHU_THEONGAY '10-10-2020'

insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000001', '2020-10-10', 1200000)
insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000002', '2020-11-10', 1300000)
insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000003', '2020-10-10', 1400000)
insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000004', '2020-10-20', 1500000)
insert DOANH_THU(MACN, NGAY_THONG_KE, DOANH_THU) values ('CN000005', '2020-12-10', 1600000)
