USE QUANLYCONCUNG
GO

SELECT *
FROM SAN_PHAM SP
WHERE SP.MASP = 'SP000987'

SELECT * 
FROM DON_HANG DH
WHERE DH.MADH = 'KH001039'

SELECT DH.MADH, DH.MAKH, SP.TEN_SP, CTDH.SO_LUONG_MUA, CTDH.GIAM_GIA, CTDH.THANH_TIEN_MUA
FROM CHI_TIET_DON_HANG CTDH JOIN DON_HANG DH ON DH.MADH = CTDH.MADH
	JOIN SAN_PHAM SP ON SP.MASP = CTDH.MASP

