USE QUANLYCONCUNG
GO

--1. DON_HANG(TG_LAP_DH)
SELECT DH.*, NV.TEN_NV FROM DON_HANG DH JOIN NHAN_VIEN NV ON DH.MANV = NV.MANV
WHERE DATEADD(dd, 0, DATEDIFF(dd, 0, TG_LAP_DH)) = '2020-10-1' 

GO
SELECT DH.*, NV.TEN_NV FROM DON_HANG_INDEX DH JOIN NHAN_VIEN NV ON DH.MANV = NV.MANV
WHERE DATEADD(dd, 0, DATEDIFF(dd, 0, TG_LAP_DH)) = '2020-10-1' 
GO
--2. CHI_NHANH(TP_TINH, QUAN_TP)
SELECT SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH
FROM CHI_NHANH CN 
WHERE TP_TINH = 'Kon Tum' and QUAN_TP = '2'
GO
SELECT SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH
FROM CHI_NHANH_INDEX CN 
WHERE TP_TINH = 'Kon Tum' and QUAN_TP = '2'
GO
--3. KHACH_HANG(SDT_KH)
SELECT MAKH, TENKH, EMAIL_KH, NGSINH_KH, TONG_DIEM_TICH_LUY, MAT_KHAU, TAI_KHOAN
FROM KHACH_HANG WHERE SDT_KH = '0844136463'
GO
SELECT MAKH, TENKH, EMAIL_KH, NGSINH_KH, TONG_DIEM_TICH_LUY, MAT_KHAU, TAI_KHOAN 
FROM KHACH_HANG_INDEX WHERE SDT_KH = '0844136463'
GO
--4. SAN_PHAM(GIA_BAN)
SELECT *
FROM SAN_PHAM
WHERE GIA_BAN BETWEEN 200000 AND 300000
ORDER BY GIA_BAN ASC

GO

SELECT *
FROM SAN_PHAM_INDEX
WHERE GIA_BAN BETWEEN 200000 AND 300000
ORDER BY GIA_BAN ASC

--5. DON_HANG(TP_TINH, QUAN_TP)
GO
SELECT MADH, MAKH, MANV, MACN, MA_VOUCHER, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, TONG_PHI, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH, TRANG_THAI, TG_TRANG_THAI, DIEM_TICH_LUY 
FROM DON_HANG WHERE TP_TINH = N'Thái Nguyên' AND QUAN_TP = N'Bình Thạnh'
GO

SELECT MADH, MAKH, MANV, MACN, MA_VOUCHER, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, TONG_PHI, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH, TRANG_THAI, TG_TRANG_THAI, DIEM_TICH_LUY 
FROM DON_HANG_INDEX WHERE TP_TINH = N'Thái Nguyên' AND QUAN_TP = N'Bình Thạnh'
