USE QUANLYCONCUNG 
GO


--Cập nhật lượt yêu thích ở bảng SAN_PHAM 
		--khi insert YEUTHICH
CREATE OR ALTER
TRIGGER TG_LUOTYEUTHICH_FOR_INSERT_YEUTHICH
ON YEUTHICH FOR INSERT
AS
BEGIN
	UPDATE SAN_PHAM
	SET LUOT_YEU_THICH += ( SELECT COUNT(MAKH)
							FROM SAN_PHAM SP JOIN inserted
							ON SP.MASP = inserted.MASP
							)
	WHERE SAN_PHAM.MASP IN (SELECT DISTINCT MASP FROM inserted)
END


	-- Khi delete YEUTHICH
GO
CREATE OR ALTER
TRIGGER TG_LUOTYEUTHICH_FOR_DELETE_YEUTHICH
ON YEUTHICH FOR DELETE
AS
BEGIN
	UPDATE SAN_PHAM
	SET LUOT_YEU_THICH -= ( SELECT COUNT(MAKH)
							FROM SAN_PHAM SP JOIN deleted
							ON SP.MASP = deleted.MASP
							)
	WHERE SAN_PHAM.MASP IN (SELECT DISTINCT MASP FROM deleted)
END


	-- Cập nhật lượt bình luận ở bảng SAN_PHAM
	-- Khi insert BINH_LUAN
GO
CREATE OR ALTER
TRIGGER TG_LUOTBINHLUAN_FOR_INSERT_BINHLUAN
ON BINH_LUAN FOR INSERT
AS
BEGIN
	UPDATE SAN_PHAM
	SET LUOT_BINH_LUAN += ( SELECT COUNT(*)
							FROM SAN_PHAM SP JOIN inserted
							ON SP.MASP = inserted.MASP
							)
	WHERE SAN_PHAM.MASP IN (SELECT DISTINCT MASP FROM inserted)
END

	-- Khi delete BINH_LUAN
GO
CREATE OR ALTER
TRIGGER TG_LUOTBINHLUAN_FOR_DELETE_BINHLUAN
ON BINH_LUAN FOR DELETE
AS
BEGIN
	UPDATE SAN_PHAM
	SET LUOT_BINH_LUAN -= ( SELECT COUNT(MAKH)
							FROM SAN_PHAM SP JOIN deleted
							ON SP.MASP = deleted.MASP
							)
	WHERE SAN_PHAM.MASP IN (SELECT DISTINCT MASP FROM deleted)
END
