USE QUANLYCONCUNG
GO
SET DATEFORMAT dmy
ALTER TABLE NHAN_VIEN
ADD TONG_DON_BAN INT, TONG_TIEN_BAN MONEY

GO
CREATE PROC USP_UPDATE_TRANG_THAI
@MaDH CHAR(8), @TrangThai NVARCHAR(10), @ThoiGian DATETIME
AS
BEGIN
	DECLARE @TTBanDau NVARCHAR(10), @TGBanDau DATETIME
	SELECT @TTBanDau = DH.TRANG_THAI, @TGBanDau = DH.TG_TRANG_THAI
	FROM DON_HANG DH
	WHERE DH.MADH = @MaDH
	IF (@TGBanDau > @ThoiGian)
	BEGIN
		PRINT N'LỖI: Thời gian trạng thái mới < Thời gian trạng thái hiện tại'
		RETURN 1 -- Không thành công
	END
	IF (@TTBanDau IN (N'Đã giao', N'Đã hủy'))
	BEGIN
		PRINT N'Không cập nhật trạng thái đơn hàng khi đơn hàng đã giao / đã hủy'
		RETURN 1
	END
	IF (@TrangThai = N'Chờ giao' AND @TTBanDau IS NOT NULL)
	BEGIN
		PRINT N'Trạng thái phải cập nhật theo thứ tự: Chờ giao -> Đã giao/Đã hủy'
		RETURN 1
	END
	UPDATE DON_HANG SET TRANG_THAI = @TrangThai, TG_TRANG_THAI = @ThoiGian
	WHERE MADH = @MaDH
	RETURN 0 -- Cập nhật thành công
END
GO
CREATE TRIGGER TG_DEL_DH
ON DON_HANG FOR DELETE
AS
BEGIN
	UPDATE NHAN_VIEN
	SET TONG_DON_BAN-= (SELECT COUNT(*) FROM deleted 
						WHERE deleted.MANV = NHAN_VIEN.MANV),
	TONG_TIEN_BAN-= (SELECT SUM(PHI_SAN_PHAM)
							FROM deleted
							WHERE deleted.MANV = NHAN_VIEN.MANV
							)
	WHERE NHAN_VIEN.MANV IN (SELECT DISTINCT deleted.MANV
										FROM deleted)
END
GO
CREATE TRIGGER TG_INS_DON_HANG
ON DON_HANG FOR INSERT
AS
BEGIN
	UPDATE NHAN_VIEN
	SET TONG_DON_BAN +=(SELECT COUNT(*) FROM inserted
						WHERE inserted.MANV = NHAN_VIEN.MANV),
	TONG_TIEN_BAN += (SELECT SUM(PHI_SAN_PHAM)
							FROM inserted
							WHERE inserted.MANV = NHAN_VIEN.MANV
							)
	WHERE NHAN_VIEN.MANV IN (SELECT DISTINCT inserted.MANV
										FROM inserted)
	UPDATE DON_HANG
	SET SO_NHA_DUONG = DC.SO_NHA_DUONG, PHUONG_XA = DC.PHUONG_XA, QUAN_TP = DC.QUAN_TP, TP_TINH = DC.TP_TINH
	FROM DIA_CHI_KH DC JOIN inserted ON inserted.MAKH = DC.MAKH
	WHERE MAC_DINH = 1 AND DON_HANG.MADH = inserted.MADH
END

----------------------
-- Mỗi khách hàng chỉ có duy nhất 1 địa chỉ mặc định
GO
CREATE PROC USP_ADD_DIA_CHI_MAC_DINH
@MaKH CHAR(8), @STT INT
AS
BEGIN
	UPDATE DIA_CHI_KH SET MAC_DINH = 1 WHERE MAKH = @MaKH AND STT = @STT
	UPDATE DIA_CHI_KH SET MAC_DINH = 0 WHERE MAKH = @MaKH AND STT != @STT
END
GO
-- Hiệu suất làm việc của nhân viên thay đổi khi update MANV (nhân viên quản lý đơn hàng) của bảng DON_HANG
-- Update nhân viên phụ trách đơn hàng
CREATE PROC USP_UPDATE_NV_DH
@NVSau CHAR(8), @MaDH CHAR(8)
AS
BEGIN
	DECLARE @NVBanDau CHAR(8), @TongTien MONEY
	SELECT @NVBanDau = MANV, @TongTien = PHI_SAN_PHAM FROM DON_HANG
	WHERE MADH = @MaDH

	IF (@NVBanDau = @NVSau)
	BEGIN
		PRINT N'Nhân viên không thay đổi!'
		RETURN 0 -- Thành công
	END
	UPDATE NHAN_VIEN SET TONG_DON_BAN -=1, TONG_TIEN_BAN -= @TongTien
	WHERE MANV = @NVBanDau
	UPDATE NHAN_VIEN SET TONG_DON_BAN +=1, TONG_TIEN_BAN += @TongTien
	WHERE MANV = @NVSau
	UPDATE DON_HANG SET MANV = @NVSau WHERE MADH = @MaDH
	RETURN 0
END



----------------- TEST --------------------------

-- cập nhật NV QLDH
SELECT MANV, TEN_NV, TONG_DON_BAN, TONG_TIEN_BAN FROM NHAN_VIEN
EXEC USP_UPDATE_NV_DH 'NV000003', 'DH000001'
SELECT MANV, TEN_NV, TONG_DON_BAN, TONG_TIEN_BAN FROM NHAN_VIEN


SELECT * FROM DON_HANG
SELECT * FROM DIA_CHI_KH
SELECT * FROM KHACH_HANG 

INSERT DIA_CHI_KH VALUES('KH000001', 1, N'123 Đường Kinh Dương Vương', N'An Lạc', N'Bình Tân',N'TP. Hồ Chí Minh', 1)
INSERT DIA_CHI_KH(MAKH, STT, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH) VALUES('KH000001', 2, N'10/16A/2 Đường An Dương Vương', N'6', N'8',N'TP. Hồ Chí Minh'),
('KH000001', 3, N'2 Đường 19A', N'5', N'6',N'TP. Hồ Chí Minh')
INSERT DIA_CHI_KH VALUES('KH000002', 1, N'12/10 Đường Lô D', N'An Bình', N'Bình Chánh',N'TP. Hồ Chí Minh',1), 
('KH000002', 2, N'365/10 Đường Thành Thái', N'4', N'10',N'TP. Hồ Chí Minh', 0)
INSERT KHACH_HANG VALUES('KH000001', N'Lê Thương', 'thuongle@gmail.com', '0980265136', NULL, 0, 'KH000001', N'thuong', NULL)
EXEC USP_ADD_DIA_CHI_MAC_DINH 'KH000001', 2
SELECT * FROM DIA_CHI_KH
SELECT * FROM DON_HANG

SELECT * FROM DON_HANG

SELECT MANV, TEN_NV, TONG_DON_BAN, TONG_TIEN_BAN FROM NHAN_VIEN
SELECT * FROM DON_HANG
INSERT DON_HANG VALUES('DH000001', 'KH000001', 'NV000001', NULL, NULL, 200000, 15000, 15000, 'VISA', 200000, NULL, NULL, NULL, NULL, '29/11/2021', NULL, NULL)
INSERT DON_HANG VALUES('DH000002', 'KH000001', 'NV000002', NULL, NULL, 510000, 15000, 15000, 'VISA', 510000, NULL, NULL, NULL, NULL, '1/12/2021', NULL, NULL),
('DH000003', 'KH000001', 'NV000002', NULL, NULL, 1000000, 30000, 10000, 'COD', 1020000, NULL, NULL, NULL, NULL, '2/12/2021', NULL, NULL)
INSERT DON_HANG VALUES('DH000004', 'KH000001', 'NV000001', NULL, NULL, 200000, 30000, 0, 'COD', 230000, NULL, NULL, NULL, NULL, '1/12/2021', NULL, NULL)
SELECT * FROM DON_HANG
DELETE FROM DON_HANG
EXEC USP_UPDATE_TRANG_THAI 'DH000001', N'Đã hủy', '1/12/2021'
SELECT * FROM NHAN_VIEN
--------------------------------------------------------
GO
CREATE TRIGGER TG_DON_HANG_NV_CN
ON DON_HANG FOR INSERT
AS
BEGIN
	UPDATE DON_HANG SET MACN = (SELECT NV.MACN
								FROM NHAN_VIEN NV
								WHERE NV.MANV = DON_HANG.MANV
								)
	WHERE MANV IN (SELECT DISTINCT inserted.MANV
					FROM inserted)
END