USE QUANLYCONCUNG

--trigger DIEM TICH LUY
GO
CREATE 
--ALTER
TRIGGER TRG_DIEMTICHLUY_FOR_INSERT_DONHANG
ON DON_HANG
FOR INSERT
AS
BEGIN
	DECLARE @PHI_GIAM INT
	SET @PHI_GIAM = (SELECT DH.PHI_GIAM
					 FROM DON_HANG DH JOIN inserted
					 ON DH.MADH = inserted.MADH) 
	IF @PHI_GIAM > 0 
	BEGIN
		UPDATE DON_HANG
		SET DIEM_TICH_LUY = 0
		WHERE MADH IN (SELECT MADH FROM inserted)

		RETURN
	END

	DECLARE @PHAN_TRAM INT
	SET @PHAN_TRAM = (SELECT T.PHAN_TRAM_TICH_LUY
					 FROM THE T JOIN KHACH_HANG KH
					 ON T.MA_THE = KH.MA_THE
					 JOIN inserted
					 ON KH.MAKH = inserted.MAKH ) 

	DECLARE @DIEM INT
	SET @DIEM = ( SELECT DH.PHI_SAN_PHAM * @PHAN_TRAM / 100 
					FROM DON_HANG DH
					JOIN inserted 
					ON inserted.MADH = DH.MADH )
	
	--UPDATE DIEM_TICH_LUY CHO DON_HANG
	UPDATE DON_HANG
	SET DIEM_TICH_LUY = @DIEM
	WHERE MADH IN (SELECT MADH FROM inserted)

	--UPDATE TONG_DIEM_TICH_LUY CHO KHACH_HANG
	UPDATE KHACH_HANG
	SET TONG_DIEM_TICH_LUY += @DIEM
	WHERE MAKH IN (SELECT DISTINCT MAKH FROM inserted)
END

GO
CREATE 
--ALTER
TRIGGER TRG_DIEMTICHLUY_FOR_UPDATE_DONHANG
ON DON_HANG
FOR UPDATE
AS
BEGIN
	DECLARE @PHI_GIAM INT
	SET @PHI_GIAM = (SELECT DH.PHI_GIAM
					 FROM DON_HANG DH JOIN inserted
					 ON DH.MADH = inserted.MADH) 

	DECLARE @PHAN_TRAM INT
	SET @PHAN_TRAM = (SELECT T.PHAN_TRAM_TICH_LUY
					 FROM THE T JOIN KHACH_HANG KH
					 ON T.MA_THE = KH.MA_THE
					 JOIN inserted
					 ON KH.MAKH = inserted.MAKH ) 
	
	DECLARE @DIEM_CU INT
	SET @DIEM_CU = (SELECT DH.DIEM_TICH_LUY
					 FROM DON_HANG DH
					 JOIN deleted
					 ON DH.MADH = deleted.MADH)

	DECLARE @DIEM_MOI INT
	SET @DIEM_MOI = ( SELECT DH.PHI_SAN_PHAM * @PHAN_TRAM / 100 
					FROM DON_HANG DH
					JOIN inserted 
					ON inserted.MADH = DH.MADH )
	
	

	IF @PHI_GIAM > 0 
	BEGIN
		UPDATE DON_HANG
		SET DIEM_TICH_LUY = 0
		WHERE MADH IN (SELECT DISTINCT MADH FROM inserted)

		UPDATE KHACH_HANG
		SET TONG_DIEM_TICH_LUY -= @DIEM_CU
		WHERE MAKH IN (SELECT MAKH FROM inserted)

		RETURN
	END
	
	--UPDATE DIEM_TICH_LUY CHO DON_HANG
	UPDATE DON_HANG
	SET DIEM_TICH_LUY = @DIEM_MOI
	WHERE MADH IN (SELECT DISTINCT MADH FROM inserted)

	--UPDATE TONG_DIEM_TICH_LUY CHO KHACH_HANG
	UPDATE KHACH_HANG
	SET TONG_DIEM_TICH_LUY = TONG_DIEM_TICH_LUY - @DIEM_CU + @DIEM_MOI
	WHERE MAKH IN (SELECT MAKH FROM inserted)
END

GO
CREATE 
--ALTER
TRIGGER TRG_DIEMTICHLUY_FOR_DELETE_DONHANG
ON DON_HANG
FOR DELETE
AS
BEGIN
	--UPDATE TONG_DIEM_TICH_LUY CHO KHACH_HANG
	UPDATE KHACH_HANG
	SET TONG_DIEM_TICH_LUY -= (SELECT deleted.DIEM_TICH_LUY
								FROM deleted JOIN KHACH_HANG KH 
								ON KH.MAKH = deleted.MAKH) 
	WHERE MAKH IN (SELECT MAKH FROM deleted)
END


--DROP TRIGGER TRG_test

--for test
update DON_HANG
SET DIEM_TICH_LUY = 0
UPDATE KHACH_HANG
SET TONG_DIEM_TICH_LUY = 0

INSERT THE(MA_THE, LOAI_THE, PHAN_TRAM_TICH_LUY) VALUES ('T0000001', N'Thẻ thường', 1)

INSERT dbo.DON_HANG(MADH, MAKH, MANV, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, TONG_PHI, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH, TRANG_THAI, TG_TRANG_THAI) VALUES (N'DH000001', 'KH000001', 'NV000938', 120000, 40000, 0, N'ZaloPay', 160000, N'42/64 Đường số 36	 ', N'Bến Thành', N'Phục Hoà', N'Long An', '1990-02-20 19:12:22.900', N'Q33', '7155-12-08 07:29:17.850')
INSERT dbo.DON_HANG(MADH, MAKH, MANV, PHI_SAN_PHAM, PHI_VAN_CHUYEN, PHI_GIAM, HINH_THUC_THANH_TOAN, TONG_PHI, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH, TG_LAP_DH, TRANG_THAI, TG_TRANG_THAI) VALUES (N'DH000000', 'KH000001', 'NV000937', 580000, 47000, 0, N'ZaloPay', 627000, N'42/64 Đường số 36	 ', N'Bến Thành', N'Phục Hoà', N'Long An', '1990-02-20 19:12:22.900', N'Q33', '7155-12-08 07:29:17.850')

UPDATE DON_HANG
SET PHI_GIAM = 1000
WHERE MADH = 'DH000000'

DELETE FROM DON_HANG
WHERE MADH = 'DH000001'

DELETE FROM DON_HANG
WHERE MADH = 'DH000000'


--TRIGGER
CREATE TRIGGER TG_DON_HANG_NV_CN
ON DON_HANG FOR INSERT
AS
BEGIN
	UPDATE DON_HANG SET MACN = (SELECT NV.MACN
								FROM NHAN_VIEN NV
								WHERE NV.MANV = DON_HANG.MANV
								)
	WHERE MANV IN (SELECT DISTINCT inserted.MANV
					FROM inserted)
END