CREATE DATABASE QUANLYCONCUNG
GO

USE QUANLYCONCUNG
GO

CREATE TABLE KHACH_HANG (
	MAKH CHAR(8),
	TENKH NVARCHAR(100),
	EMAIL_KH VARCHAR(60),
	SDT_KH CHAR(10),
	NGSINH_KH DATE,
	LOAI_KH BIT,
	MAT_KHAU VARCHAR(50),
	TAI_KHOAN VARCHAR(50)

	CONSTRAINT PK_KHACH_HANG PRIMARY KEY(MAKH)
)
GO

CREATE TABLE DIA_CHI_KH (
	MAKH CHAR(8),
	STT INT,
	SO_NHA_DUONG NVARCHAR(30),
	PHUONG_XA NVARCHAR(20),
	QUAN_TP NVARCHAR(20),
	TP_TINH NVARCHAR(20),
	MAC_DINH BIT,
	
	CONSTRAINT FK_DC_KH FOREIGN KEY(MAKH) REFERENCES KHACH_HANG(MAKH),
	CONSTRAINT PK_DIA_CHI_KH PRIMARY KEY(MAKH, STT)
)

GO
CREATE TABLE EM_BE (
	ID_BE CHAR(8),
	ID_BAME CHAR(8),
	TEN_BE NVARCHAR(100),
	NGSINH_BE DATE,

	CONSTRAINT FK_BE_BAME FOREIGN KEY (ID_BAME) REFERENCES KHACH_HANG(MAKH),
	CONSTRAINT PK_EM_BE PRIMARY KEY(ID_BE)
)

GO
CREATE TABLE THUONG_HIEU (
	MATH CHAR(8),
	TEN_TH NVARCHAR(20),
	MO_TA NVARCHAR(300),

	CONSTRAINT PK_THUONG_HIEU PRIMARY KEY(MATH)
)

GO 
CREATE TABLE LOAI_HANG (
		MALH CHAR(8),
		TEN_LH NVARCHAR(30),

		CONSTRAINT PK_LOAI_HANG PRIMARY KEY(MALH)
)


GO
CREATE TABLE VOUCHER (
	MA_VOUCHER CHAR(8),
	LOAI_AP_DUNG NVARCHAR(100),
	PHAN_TRAM_GIAM_GIA FLOAT,
	GIAM_TOI_DA MONEY,
	TG_BAT_DAU DATETIME,
	TG_KET_THUC DATETIME,
	SO_LUONG_AP_DUNG INT,

	CONSTRAINT PK_VOUCHER PRIMARY KEY (MA_VOUCHER)
)

GO
CREATE TABLE CHI_NHANH (
	MACN CHAR(8),
	NVQL CHAR(8),
	SDT_CN CHAR(10),
	SO_NHA_DUONG NVARCHAR(100),
	PHUONG_XA NVARCHAR(100),
	QUAN_TP NVARCHAR(60),
	TP_TINH NVARCHAR(60),

	CONSTRAINT PK_CNHANH PRIMARY KEY(MACN)
)

GO
CREATE TABLE NHAN_VIEN (
	MANV CHAR(8),
	TEN_NV NVARCHAR(100),
	SDT CHAR(10),
	CMND VARCHAR(12),
	NGAY_BAT_DAU_LAM DATE,
	NGAY_NGHI_VIEC DATE,
	SO_NHA_DUONG NVARCHAR(100),
	PHUONG_XA NVARCHAR(100),
	QUAN_TP NVARCHAR(60),
	TP_TINH NVARCHAR(60),
	MACN CHAR(8),

	CONSTRAINT FK_NV_CN FOREIGN KEY (MACN) REFERENCES CHI_NHANH (MACN),
	CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (MANV)
)

GO
ALTER TABLE CHI_NHANH ADD CONSTRAINT FK_CN_NVQL FOREIGN KEY(NVQL) REFERENCES NHAN_VIEN (MANV)

GO
CREATE TABLE DON_HANG (
	MADH CHAR(8) PRIMARY KEY,
	MAKH CHAR(8),
	MANV CHAR(8),
	MA_VOUCHER CHAR(8),
	PHI_SAN_PHAM MONEY,
	PHI_VAN_CHUYEN MONEY,
	PHI_GIAM MONEY,
	HINH_THUC_THANH_TOAN NVARCHAR(50),
	TONG_PHI MONEY,
	SO_NHA_DUONG NVARCHAR(255),
	PHUONG_XA NVARCHAR(50),
	QUAN_TP NVARCHAR(50),
	TP_TINH NVARCHAR(50),
	TG_LAP_DH DATETIME,

	CONSTRAINT FK_DH_KH FOREIGN KEY (MAKH)  REFERENCES KHACH_HANG(MAKH),
	CONSTRAINT FK_DH_NV  FOREIGN KEY (MANV)  REFERENCES NHAN_VIEN (MANV),
	CONSTRAINT FK_DH_VOUCHER FOREIGN KEY (MA_VOUCHER)  REFERENCES VOUCHER(MA_VOUCHER)
)

GO
CREATE TABLE TRANG_THAI_DON_HANG (
	MADH CHAR(8),
	TRANG_THAI NVARCHAR(10),
	THOI_GIAN DATETIME,

	CONSTRAINT FK_TT_DH FOREIGN KEY(MADH) REFERENCES DON_HANG(MADH),
	CONSTRAINT PK_TRANG_THAI_DON_HANG PRIMARY KEY(MADH, TRANG_THAI)
)

GO
CREATE TABLE SAN_PHAM (
	MASP CHAR(8),
	MALH CHAR(8),
	MATH CHAR(8),
	TEN_SP NVARCHAR(100),
	HINH_ANH VARCHAR(500),
	MO_TA NVARCHAR(1000),
	LUOT_YEU_THICH INT,
	LUOT_BINH_LUAN INT,
	GIA_BAN MONEY,

	CONSTRAINT PK_SAN_PHAM PRIMARY KEY(MASP),
	CONSTRAINT FK_SP_LH FOREIGN KEY (MALH) REFERENCES LOAI_HANG (MALH),
	CONSTRAINT FK_SP_TH FOREIGN KEY (MATH) REFERENCES THUONG_HIEU (MATH)
)

GO
CREATE TABLE CHI_TIET_DON_HANG (
	MADH CHAR(8),
	MASP CHAR(8),
	SO_LUONG_MUA INT,
	GIAM_GIA MONEY,
	THANH_TIEN_MUA MONEY,

	CONSTRAINT FK_CTDH_DH FOREIGN KEY (MADH) REFERENCES DON_HANG(MADH),
	CONSTRAINT FK_CTDH_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP),
	CONSTRAINT PK_DH_SP PRIMARY KEY (MADH,MASP)
)

GO
CREATE TABLE NHA_CUNG_CAP (
	MANCC CHAR(8),
	MATH CHAR(8),
	TEN_NCC NVARCHAR(100),
	SO_NHA_DUONG NVARCHAR(100),
	PHUONG_XA NVARCHAR(100),
	QUAN_TP NVARCHAR(60),
	TP_TINH NVARCHAR(60),

	CONSTRAINT PK_NCC PRIMARY KEY (MANCC),
	CONSTRAINT FK_NCC_TH FOREIGN KEY(MATH)  REFERENCES THUONG_HIEU(MATH)
)

GO
CREATE TABLE PHIEU_NHAP_HANG (
	MAPN CHAR(8),
	MANCC CHAR(8),
	NGAY_LAP DATETIME,
	TONG_TIEN_NHAP MONEY,
	TONG_SO_MAT_HANG INT,

	CONSTRAINT FK_PN_NCC FOREIGN KEY(MANCC) REFERENCES NHA_CUNG_CAP(MANCC),
	CONSTRAINT PK_PHIEU_NHAP_HANG PRIMARY KEY(MAPN)
)

GO
CREATE TABLE CHI_TIET_NHAP_HANG (
	MAPN CHAR(8),
	MASP CHAR(8),
	SO_LUONG_NHAP INT,
	THANH_TIEN_NHAP MONEY,

	CONSTRAINT PK_CT_NHAP_HANG PRIMARY KEY(MAPN, MASP),
	CONSTRAINT FK_CTNH_PN FOREIGN KEY(MAPN) REFERENCES PHIEU_NHAP_HANG(MAPN),
	CONSTRAINT FK_CTNH_SP FOREIGN KEY(MASP) REFERENCES SAN_PHAM(MASP)
)

GO
CREATE TABLE BAN (
	MASP CHAR(8),
	MACN CHAR(8),
	SO_LUONG_TON INT,

	CONSTRAINT PK_BAN PRIMARY KEY(MASP, MACN),
	CONSTRAINT FK_BAN_SP FOREIGN KEY(MASP) REFERENCES SAN_PHAM (MASP),
	CONSTRAINT FK_BAN_CN FOREIGN KEY(MACN) REFERENCES CHI_NHANH (MACN)
)

GO
CREATE TABLE BINH_LUAN (
	MAKH CHAR(8),
	MASP CHAR(8),
	NOI_DUNG NVARCHAR(1000),
	NGAY_DANG DATETIME,

	CONSTRAINT FK_BL_KH FOREIGN KEY(MAKH) REFERENCES KHACH_HANG(MAKH),
	CONSTRAINT FK_BL_SP FOREIGN KEY(MASP) REFERENCES SAN_PHAM(MASP),
	CONSTRAINT PK_BINH_LUAN PRIMARY KEY(MAKH, MASP)
)

GO
CREATE TABLE HIEU_SUAT_LAM_VIEC (
	MANV CHAR(8),
	TONG_DON_BAN INT,
	TONG_TIEN_BAN_DUOC INT,
	TONG_SO_SP_BAN INT,

	CONSTRAINT FK_HIEUSUAT_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV),
	CONSTRAINT PK_HIEU_SUAT PRIMARY KEY(MANV)
)

GO
CREATE TABLE CHAM_CONG (
	MANV CHAR(8),
	TG_VAO_CA DATETIME,
	TG_RA_CA DATETIME,

	CONSTRAINT PK_CHAM_CONG PRIMARY KEY(MANV, TG_VAO_CA, TG_RA_CA),
	CONSTRAINT FK_CC_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV)
)
